### ISSUE TITLE
Demonstrate that the skeleton can walk

### ISSUE THREAD

**Issue by iaindillingham** [opensafely/open-pathology#18]
To demonstrate that the skeleton can walk, each of the following steps must be complete:

- [ ] Motivating problem
- [ ] Codelist on OpenCodelists (#5)
- [ ] Study code (#4)
- [ ] Approved OpenSAFELY Application (#9)
- [ ] Application and project on OS Jobs
- [ ] Workspace on OS Jobs (#3)
- [ ] Released measure table on OS Jobs
- [ ] Published measure table on OS Jobs
- [ ] Dashboard code (#2)
- [ ] Dashboard app

For more information, see [`docs/walking_skeleton.md`](https://github.com/opensafely/open-pathology/blob/main/docs/walking_skeleton.md).
